paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        '200':
          description: A list of products
          content: 
            application/json: 
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
  /api/products/{pid}:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      parameters: 
      - name: pid
        in: path
        required: true,
        description: id del producto que se desea solicitar
        schema: 
          $type: string
      responses:
        '200':
          description: Producto encontrado
          content: 
            application/json: 
              schema:
                $ref: '#components/schemas/Product'
    put: 
      summary: Actualiza un product a partir de su id
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: id del producto que se desea actualizar
        schema:
          $type: string
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProduct'


components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerado de mongo
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripcion del producto
        code:
          type: number
          description: codigo del producto, este campo es unico
        price:
          type: number
          description: Precio del producto
        status:
          type: boolean
          description: Estado del producto
        stock:
          type: number
          description: Stock del producto
        category:
          type: string
          description: Categoria del producto
        thumbnails:
          type: array
          items:
            type: string
          description: Imagen/es del producto
        owner:
          type: string
          description: Owner del producto
      example:
        title: "producto swagger"
        description: "descripcion del producto swagger"
        code: "100"
        price: 5250
        status: true
        stock: 9
        category: "test"
        thumbnails: []
        owner: "admin"
        _id: "6684112515f00de9bf77cee9"
  requestBodies:
    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripcion del producto
        code:
          type: number
          description: codigo del producto, este campo es unico
        price:
          type: number
          description: Precio del producto
        status:
          type: boolean
          description: Estado del producto
        stock:
          type: number
          description: Stock del producto
        category:
          type: string
          description: Categoria del producto
        thumbnails:
          type: array
          items:
            type: string
          description: Imagen/es del producto
      example:
          title: "producto swagger"
          description: "descripcion del producto swagger"
          code: "100"
          price: 5250
          status: true
          stock: 9
          category: "test"
          thumbnails: [
            "imagen.png"
          ]

