export const ErrorCodes = {
    ROUTING_ERROR : 'ROUTING_ERROR',
    INVALID_TYPES_ERROR: 'INVALID_TYPES_ERROR',
    CONNECTION_DATABASE_ERROR:'CONNECTION_DATABASE_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
    AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
    NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
}