export const ErrorCodes = {
  INVALID_TYPES_ERROR: 'INVALID_TYPES_ERROR',
  INVALID_ID:'INVALID_ID',
  INVALID_EMAIL:'INVALID_EMAIL',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_CODE: 'DUPLICATE_CODE',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
  ROUTING_ERROR: 'ROUTING_ERROR',
  NOT_PERMISSION_DELETE_PRODUCT:'NOT_PERMISSION_DELETE_PRODUCT',
  /*
  CONNECTION_DATABASE_ERROR: 'CONNECTION_DATABASE_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  PAYMENT_ERROR: 'PAYMENT_ERROR',
  INVENTORY_ERROR: 'INVENTORY_ERROR',
  SHIPPING_ERROR: 'SHIPPING_ERROR',
  RATE_LIMITING_ERROR: 'RATE_LIMITING_ERROR',
  */ 
};
